apiVersion: batch/v1
kind: Job
metadata:
  name: process-err431606
spec:
  template:
    metadata:
      name: process-err431606
    spec:
      containers:
      - name: process-err431606
        image: gcr.io/pici-1286/mz-rna-pipeline:latest
        command: ["process", "ERR431606" , "Homo_sapiens.GRCh38.cdna.all.kallisto.idx", "ERR431606", "25G", "3"]
        resources:
          limits:
            cpu: 3
            memory: 25Gi
          requests:
            cpu: 3
            memory: 25Gi
        volumeMounts:
        #- mountPath: /working
        - mountPath: /data
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs          
      restartPolicy: Never
