# DOES NOT WORK!
apiVersion: v1
desiredState:
  manifest:
    containers:
      - name: web
        image: dockerfile/nginx
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/var/www/html"
        ports:
          - name: web
            containerPort: 80
            protocol: tcp
    id: web
    version: v1
    volumes:
      - name: nfs
        source:
          nfs:
            server: mz-nfs-vm
            path: "/mz-data"
            readOnly: false
id: web
kind: Pod