apiVersion: batch/v1
kind: Job
metadata:
  name: process-err431579
spec:
  template:
    metadata:
      name: process-err431579
    spec:
      containers:
      - name: process-err431579
        image: gcr.io/pici-1286/mz-rna-pipeline:latest
        command: ["process", "ERR431579" , "Homo_sapiens.GRCh38.cdna.all.kallisto.idx", "ERR431579"]
        resources:
          limits:
            cpu: 3
            memory: 25Gi
          requests:
            cpu: 3
            memory: 25Gi
        volumeMounts:
        - mountPath: /working
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs          
      restartPolicy: Never
