apiVersion: batch/v1
kind: Job
metadata:
  name: process-{jobid}
spec:
  template:
    metadata:
      name: process-{jobid}
    spec:
      containers:
      - name: process-{jobid}
        image: gcr.io/pici-1286/mz-rna-pipeline:latest
        command: ["process", "{filename}" , "Homo_sapiens.GRCh38.cdna.all.kallisto.idx", "{outputname}"]
        resources:
          limits:
            cpu: 3
            memory: 25Gi
          requests:
            cpu: 3
            memory: 25Gi
        volumeMounts:
        - mountPath: /working
          name: nfs
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs          
      restartPolicy: Never
